spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/authdb?createDatabaseIfNotExist=true&useSSL=false
    password:
  h2:
    console:
      enabled: 'true'
    application:
      name: auth-location
  liquibase:
    enabled: 'true'
    change-log: classpath:db/changelog/changelog-master.xml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: 'true'
    hibernate:
      ddl-auto: create
    show-sql: 'true'
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

